name: Create & Upload Docker Image to GHCR

on:
  push:
    branches: [main]
    paths:
      # only push to changes in apps/bot, apps/server, or the dockerfiles
      - "apps/bot/**"
      - "apps/server/**"
      - "*.Dockerfile"
      - "docker-compose.yml"
      - "package.json"
      - ".dockerignore"
      - "!*.md"
      - ".github/workflows/docker-images.yml" # this file

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ Checkout repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: âœï¸ Write bot-config.yml
        run: echo "{{ secrets.BOT_CONFIG_YML }}" > bot-config.yml

      - name: âœï¸ Write server-config.yml
        run: echo "{{ secrets.SERVER_CONFIG_YML }}" > server-config.yml

      - name: ğŸ”– Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: ğŸ³ Build and push Docker image
        uses: joshuanianji/publish_docker-compose@0535aff7b628028f2583706d5356be7862c021b3
        with:
          docker_compose: "docker-compose.yml"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
